spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin
  application:
    name: product-service


springdoc:
  swagger-ui:
    url: /swagger-ui.html
  api-docs:
    path: /api-docs
